//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BakeryEntities1 : DbContext
    {
        public BakeryEntities1()
            : base("name=BakeryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
    
        public virtual int usp_Login(string personEmail, string personPhone)
        {
            var personEmailParameter = personEmail != null ?
                new ObjectParameter("PersonEmail", personEmail) :
                new ObjectParameter("PersonEmail", typeof(string));
    
            var personPhoneParameter = personPhone != null ?
                new ObjectParameter("PersonPhone", personPhone) :
                new ObjectParameter("PersonPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_Login", personEmailParameter, personPhoneParameter);
        }
    }
}
